// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ErrorCode.proto

package org.tinygame.herostory.msg;

public final class ErrorCodeProto {
  private ErrorCodeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.game.message.proto.OPErrorCode}
   */
  public enum OPErrorCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *成功
     * </pre>
     *
     * <code>SUCCESS = 0;</code>
     */
    SUCCESS(0),
    /**
     * <pre>
     *动态错误标识
     * </pre>
     *
     * <code>DYNAMIC_ERROR = -1;</code>
     */
    DYNAMIC_ERROR(-1),
    /**
     * <pre>
     *服务器繁忙，当前操作不能完成
     * </pre>
     *
     * <code>SERVER_FAIL = -1000;</code>
     */
    SERVER_FAIL(-1000),
    /**
     * <pre>
     *失败
     * </pre>
     *
     * <code>FAIL = -10000;</code>
     */
    FAIL(-10000),
    /**
     * <pre>
     *桌子已经清理干净
     * </pre>
     *
     * <code>TABLE_IS_CLEAN = -10001;</code>
     */
    TABLE_IS_CLEAN(-10001),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *成功
     * </pre>
     *
     * <code>SUCCESS = 0;</code>
     */
    public static final int SUCCESS_VALUE = 0;
    /**
     * <pre>
     *动态错误标识
     * </pre>
     *
     * <code>DYNAMIC_ERROR = -1;</code>
     */
    public static final int DYNAMIC_ERROR_VALUE = -1;
    /**
     * <pre>
     *服务器繁忙，当前操作不能完成
     * </pre>
     *
     * <code>SERVER_FAIL = -1000;</code>
     */
    public static final int SERVER_FAIL_VALUE = -1000;
    /**
     * <pre>
     *失败
     * </pre>
     *
     * <code>FAIL = -10000;</code>
     */
    public static final int FAIL_VALUE = -10000;
    /**
     * <pre>
     *桌子已经清理干净
     * </pre>
     *
     * <code>TABLE_IS_CLEAN = -10001;</code>
     */
    public static final int TABLE_IS_CLEAN_VALUE = -10001;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static OPErrorCode valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static OPErrorCode forNumber(int value) {
      switch (value) {
        case 0: return SUCCESS;
        case -1: return DYNAMIC_ERROR;
        case -1000: return SERVER_FAIL;
        case -10000: return FAIL;
        case -10001: return TABLE_IS_CLEAN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<OPErrorCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        OPErrorCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<OPErrorCode>() {
            public OPErrorCode findValueByNumber(int number) {
              return OPErrorCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.tinygame.herostory.msg.ErrorCodeProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final OPErrorCode[] VALUES = values();

    public static OPErrorCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private OPErrorCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.game.message.proto.OPErrorCode)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017ErrorCode.proto\022\026com.game.message.prot" +
      "o*\200\001\n\013OPErrorCode\022\013\n\007SUCCESS\020\000\022\032\n\rDYNAMI" +
      "C_ERROR\020\377\377\377\377\377\377\377\377\377\001\022\030\n\013SERVER_FAIL\020\230\370\377\377\377\377" +
      "\377\377\377\001\022\021\n\004FAIL\020\360\261\377\377\377\377\377\377\377\001\022\033\n\016TABLE_IS_CLEA" +
      "N\020\357\261\377\377\377\377\377\377\377\001B,\n\032org.tinygame.herostory.m" +
      "sgB\016ErrorCodeProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
