// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Player.proto

package org.tinygame.herostory.msg;

public final class PlayerProto {
  private PlayerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlayerInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.game.message.proto.PlayerInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *玩家Id
     * </pre>
     *
     * <code>int64 playerId = 1;</code>
     * @return The playerId.
     */
    long getPlayerId();

    /**
     * <pre>
     *现金红包
     * </pre>
     *
     * <code>int32 cash = 2;</code>
     * @return The cash.
     */
    int getCash();

    /**
     * <pre>
     *钞票
     * </pre>
     *
     * <code>int64 money = 3;</code>
     * @return The money.
     */
    long getMoney();

    /**
     * <pre>
     *元宝
     * </pre>
     *
     * <code>int32 gold = 4;</code>
     * @return The gold.
     */
    int getGold();

    /**
     * <pre>
     *名字
     * </pre>
     *
     * <code>string name = 5;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <pre>
     *名字
     * </pre>
     *
     * <code>string name = 5;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     *头像
     * </pre>
     *
     * <code>int32 head = 6;</code>
     * @return The head.
     */
    int getHead();

    /**
     * <pre>
     *登录时间
     * </pre>
     *
     * <code>int64 loginTime = 7;</code>
     * @return The loginTime.
     */
    long getLoginTime();

    /**
     * <pre>
     *招牌
     * </pre>
     *
     * <code>int32 signboard = 8;</code>
     * @return The signboard.
     */
    int getSignboard();

    /**
     * <pre>
     *钟表
     * </pre>
     *
     * <code>int32 horologe = 9;</code>
     * @return The horologe.
     */
    int getHorologe();
  }
  /**
   * <pre>
   *玩家基本信息
   * </pre>
   *
   * Protobuf type {@code com.game.message.proto.PlayerInfo}
   */
  public static final class PlayerInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.game.message.proto.PlayerInfo)
      PlayerInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlayerInfo.newBuilder() to construct.
    private PlayerInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerInfo() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PlayerInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              playerId_ = input.readInt64();
              break;
            }
            case 16: {

              cash_ = input.readInt32();
              break;
            }
            case 24: {

              money_ = input.readInt64();
              break;
            }
            case 32: {

              gold_ = input.readInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 48: {

              head_ = input.readInt32();
              break;
            }
            case 56: {

              loginTime_ = input.readInt64();
              break;
            }
            case 64: {

              signboard_ = input.readInt32();
              break;
            }
            case 72: {

              horologe_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tinygame.herostory.msg.PlayerProto.internal_static_com_game_message_proto_PlayerInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tinygame.herostory.msg.PlayerProto.internal_static_com_game_message_proto_PlayerInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tinygame.herostory.msg.PlayerProto.PlayerInfo.class, org.tinygame.herostory.msg.PlayerProto.PlayerInfo.Builder.class);
    }

    public static final int PLAYERID_FIELD_NUMBER = 1;
    private long playerId_;
    /**
     * <pre>
     *玩家Id
     * </pre>
     *
     * <code>int64 playerId = 1;</code>
     * @return The playerId.
     */
    @java.lang.Override
    public long getPlayerId() {
      return playerId_;
    }

    public static final int CASH_FIELD_NUMBER = 2;
    private int cash_;
    /**
     * <pre>
     *现金红包
     * </pre>
     *
     * <code>int32 cash = 2;</code>
     * @return The cash.
     */
    @java.lang.Override
    public int getCash() {
      return cash_;
    }

    public static final int MONEY_FIELD_NUMBER = 3;
    private long money_;
    /**
     * <pre>
     *钞票
     * </pre>
     *
     * <code>int64 money = 3;</code>
     * @return The money.
     */
    @java.lang.Override
    public long getMoney() {
      return money_;
    }

    public static final int GOLD_FIELD_NUMBER = 4;
    private int gold_;
    /**
     * <pre>
     *元宝
     * </pre>
     *
     * <code>int32 gold = 4;</code>
     * @return The gold.
     */
    @java.lang.Override
    public int getGold() {
      return gold_;
    }

    public static final int NAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     *名字
     * </pre>
     *
     * <code>string name = 5;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *名字
     * </pre>
     *
     * <code>string name = 5;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HEAD_FIELD_NUMBER = 6;
    private int head_;
    /**
     * <pre>
     *头像
     * </pre>
     *
     * <code>int32 head = 6;</code>
     * @return The head.
     */
    @java.lang.Override
    public int getHead() {
      return head_;
    }

    public static final int LOGINTIME_FIELD_NUMBER = 7;
    private long loginTime_;
    /**
     * <pre>
     *登录时间
     * </pre>
     *
     * <code>int64 loginTime = 7;</code>
     * @return The loginTime.
     */
    @java.lang.Override
    public long getLoginTime() {
      return loginTime_;
    }

    public static final int SIGNBOARD_FIELD_NUMBER = 8;
    private int signboard_;
    /**
     * <pre>
     *招牌
     * </pre>
     *
     * <code>int32 signboard = 8;</code>
     * @return The signboard.
     */
    @java.lang.Override
    public int getSignboard() {
      return signboard_;
    }

    public static final int HOROLOGE_FIELD_NUMBER = 9;
    private int horologe_;
    /**
     * <pre>
     *钟表
     * </pre>
     *
     * <code>int32 horologe = 9;</code>
     * @return The horologe.
     */
    @java.lang.Override
    public int getHorologe() {
      return horologe_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (playerId_ != 0L) {
        output.writeInt64(1, playerId_);
      }
      if (cash_ != 0) {
        output.writeInt32(2, cash_);
      }
      if (money_ != 0L) {
        output.writeInt64(3, money_);
      }
      if (gold_ != 0) {
        output.writeInt32(4, gold_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, name_);
      }
      if (head_ != 0) {
        output.writeInt32(6, head_);
      }
      if (loginTime_ != 0L) {
        output.writeInt64(7, loginTime_);
      }
      if (signboard_ != 0) {
        output.writeInt32(8, signboard_);
      }
      if (horologe_ != 0) {
        output.writeInt32(9, horologe_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (playerId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, playerId_);
      }
      if (cash_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, cash_);
      }
      if (money_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, money_);
      }
      if (gold_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, gold_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, name_);
      }
      if (head_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, head_);
      }
      if (loginTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, loginTime_);
      }
      if (signboard_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, signboard_);
      }
      if (horologe_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, horologe_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.tinygame.herostory.msg.PlayerProto.PlayerInfo)) {
        return super.equals(obj);
      }
      org.tinygame.herostory.msg.PlayerProto.PlayerInfo other = (org.tinygame.herostory.msg.PlayerProto.PlayerInfo) obj;

      if (getPlayerId()
          != other.getPlayerId()) return false;
      if (getCash()
          != other.getCash()) return false;
      if (getMoney()
          != other.getMoney()) return false;
      if (getGold()
          != other.getGold()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (getHead()
          != other.getHead()) return false;
      if (getLoginTime()
          != other.getLoginTime()) return false;
      if (getSignboard()
          != other.getSignboard()) return false;
      if (getHorologe()
          != other.getHorologe()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PLAYERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPlayerId());
      hash = (37 * hash) + CASH_FIELD_NUMBER;
      hash = (53 * hash) + getCash();
      hash = (37 * hash) + MONEY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMoney());
      hash = (37 * hash) + GOLD_FIELD_NUMBER;
      hash = (53 * hash) + getGold();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + HEAD_FIELD_NUMBER;
      hash = (53 * hash) + getHead();
      hash = (37 * hash) + LOGINTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLoginTime());
      hash = (37 * hash) + SIGNBOARD_FIELD_NUMBER;
      hash = (53 * hash) + getSignboard();
      hash = (37 * hash) + HOROLOGE_FIELD_NUMBER;
      hash = (53 * hash) + getHorologe();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.tinygame.herostory.msg.PlayerProto.PlayerInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tinygame.herostory.msg.PlayerProto.PlayerInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tinygame.herostory.msg.PlayerProto.PlayerInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tinygame.herostory.msg.PlayerProto.PlayerInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tinygame.herostory.msg.PlayerProto.PlayerInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tinygame.herostory.msg.PlayerProto.PlayerInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tinygame.herostory.msg.PlayerProto.PlayerInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tinygame.herostory.msg.PlayerProto.PlayerInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tinygame.herostory.msg.PlayerProto.PlayerInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.tinygame.herostory.msg.PlayerProto.PlayerInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tinygame.herostory.msg.PlayerProto.PlayerInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tinygame.herostory.msg.PlayerProto.PlayerInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.tinygame.herostory.msg.PlayerProto.PlayerInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *玩家基本信息
     * </pre>
     *
     * Protobuf type {@code com.game.message.proto.PlayerInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.game.message.proto.PlayerInfo)
        org.tinygame.herostory.msg.PlayerProto.PlayerInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tinygame.herostory.msg.PlayerProto.internal_static_com_game_message_proto_PlayerInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tinygame.herostory.msg.PlayerProto.internal_static_com_game_message_proto_PlayerInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tinygame.herostory.msg.PlayerProto.PlayerInfo.class, org.tinygame.herostory.msg.PlayerProto.PlayerInfo.Builder.class);
      }

      // Construct using org.tinygame.herostory.msg.PlayerProto.PlayerInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        playerId_ = 0L;

        cash_ = 0;

        money_ = 0L;

        gold_ = 0;

        name_ = "";

        head_ = 0;

        loginTime_ = 0L;

        signboard_ = 0;

        horologe_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tinygame.herostory.msg.PlayerProto.internal_static_com_game_message_proto_PlayerInfo_descriptor;
      }

      @java.lang.Override
      public org.tinygame.herostory.msg.PlayerProto.PlayerInfo getDefaultInstanceForType() {
        return org.tinygame.herostory.msg.PlayerProto.PlayerInfo.getDefaultInstance();
      }

      @java.lang.Override
      public org.tinygame.herostory.msg.PlayerProto.PlayerInfo build() {
        org.tinygame.herostory.msg.PlayerProto.PlayerInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.tinygame.herostory.msg.PlayerProto.PlayerInfo buildPartial() {
        org.tinygame.herostory.msg.PlayerProto.PlayerInfo result = new org.tinygame.herostory.msg.PlayerProto.PlayerInfo(this);
        result.playerId_ = playerId_;
        result.cash_ = cash_;
        result.money_ = money_;
        result.gold_ = gold_;
        result.name_ = name_;
        result.head_ = head_;
        result.loginTime_ = loginTime_;
        result.signboard_ = signboard_;
        result.horologe_ = horologe_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tinygame.herostory.msg.PlayerProto.PlayerInfo) {
          return mergeFrom((org.tinygame.herostory.msg.PlayerProto.PlayerInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tinygame.herostory.msg.PlayerProto.PlayerInfo other) {
        if (other == org.tinygame.herostory.msg.PlayerProto.PlayerInfo.getDefaultInstance()) return this;
        if (other.getPlayerId() != 0L) {
          setPlayerId(other.getPlayerId());
        }
        if (other.getCash() != 0) {
          setCash(other.getCash());
        }
        if (other.getMoney() != 0L) {
          setMoney(other.getMoney());
        }
        if (other.getGold() != 0) {
          setGold(other.getGold());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getHead() != 0) {
          setHead(other.getHead());
        }
        if (other.getLoginTime() != 0L) {
          setLoginTime(other.getLoginTime());
        }
        if (other.getSignboard() != 0) {
          setSignboard(other.getSignboard());
        }
        if (other.getHorologe() != 0) {
          setHorologe(other.getHorologe());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tinygame.herostory.msg.PlayerProto.PlayerInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tinygame.herostory.msg.PlayerProto.PlayerInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long playerId_ ;
      /**
       * <pre>
       *玩家Id
       * </pre>
       *
       * <code>int64 playerId = 1;</code>
       * @return The playerId.
       */
      @java.lang.Override
      public long getPlayerId() {
        return playerId_;
      }
      /**
       * <pre>
       *玩家Id
       * </pre>
       *
       * <code>int64 playerId = 1;</code>
       * @param value The playerId to set.
       * @return This builder for chaining.
       */
      public Builder setPlayerId(long value) {
        
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *玩家Id
       * </pre>
       *
       * <code>int64 playerId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlayerId() {
        
        playerId_ = 0L;
        onChanged();
        return this;
      }

      private int cash_ ;
      /**
       * <pre>
       *现金红包
       * </pre>
       *
       * <code>int32 cash = 2;</code>
       * @return The cash.
       */
      @java.lang.Override
      public int getCash() {
        return cash_;
      }
      /**
       * <pre>
       *现金红包
       * </pre>
       *
       * <code>int32 cash = 2;</code>
       * @param value The cash to set.
       * @return This builder for chaining.
       */
      public Builder setCash(int value) {
        
        cash_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *现金红包
       * </pre>
       *
       * <code>int32 cash = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCash() {
        
        cash_ = 0;
        onChanged();
        return this;
      }

      private long money_ ;
      /**
       * <pre>
       *钞票
       * </pre>
       *
       * <code>int64 money = 3;</code>
       * @return The money.
       */
      @java.lang.Override
      public long getMoney() {
        return money_;
      }
      /**
       * <pre>
       *钞票
       * </pre>
       *
       * <code>int64 money = 3;</code>
       * @param value The money to set.
       * @return This builder for chaining.
       */
      public Builder setMoney(long value) {
        
        money_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *钞票
       * </pre>
       *
       * <code>int64 money = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMoney() {
        
        money_ = 0L;
        onChanged();
        return this;
      }

      private int gold_ ;
      /**
       * <pre>
       *元宝
       * </pre>
       *
       * <code>int32 gold = 4;</code>
       * @return The gold.
       */
      @java.lang.Override
      public int getGold() {
        return gold_;
      }
      /**
       * <pre>
       *元宝
       * </pre>
       *
       * <code>int32 gold = 4;</code>
       * @param value The gold to set.
       * @return This builder for chaining.
       */
      public Builder setGold(int value) {
        
        gold_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *元宝
       * </pre>
       *
       * <code>int32 gold = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearGold() {
        
        gold_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       *名字
       * </pre>
       *
       * <code>string name = 5;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *名字
       * </pre>
       *
       * <code>string name = 5;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *名字
       * </pre>
       *
       * <code>string name = 5;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *名字
       * </pre>
       *
       * <code>string name = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *名字
       * </pre>
       *
       * <code>string name = 5;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int head_ ;
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>int32 head = 6;</code>
       * @return The head.
       */
      @java.lang.Override
      public int getHead() {
        return head_;
      }
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>int32 head = 6;</code>
       * @param value The head to set.
       * @return This builder for chaining.
       */
      public Builder setHead(int value) {
        
        head_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>int32 head = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearHead() {
        
        head_ = 0;
        onChanged();
        return this;
      }

      private long loginTime_ ;
      /**
       * <pre>
       *登录时间
       * </pre>
       *
       * <code>int64 loginTime = 7;</code>
       * @return The loginTime.
       */
      @java.lang.Override
      public long getLoginTime() {
        return loginTime_;
      }
      /**
       * <pre>
       *登录时间
       * </pre>
       *
       * <code>int64 loginTime = 7;</code>
       * @param value The loginTime to set.
       * @return This builder for chaining.
       */
      public Builder setLoginTime(long value) {
        
        loginTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *登录时间
       * </pre>
       *
       * <code>int64 loginTime = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearLoginTime() {
        
        loginTime_ = 0L;
        onChanged();
        return this;
      }

      private int signboard_ ;
      /**
       * <pre>
       *招牌
       * </pre>
       *
       * <code>int32 signboard = 8;</code>
       * @return The signboard.
       */
      @java.lang.Override
      public int getSignboard() {
        return signboard_;
      }
      /**
       * <pre>
       *招牌
       * </pre>
       *
       * <code>int32 signboard = 8;</code>
       * @param value The signboard to set.
       * @return This builder for chaining.
       */
      public Builder setSignboard(int value) {
        
        signboard_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *招牌
       * </pre>
       *
       * <code>int32 signboard = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearSignboard() {
        
        signboard_ = 0;
        onChanged();
        return this;
      }

      private int horologe_ ;
      /**
       * <pre>
       *钟表
       * </pre>
       *
       * <code>int32 horologe = 9;</code>
       * @return The horologe.
       */
      @java.lang.Override
      public int getHorologe() {
        return horologe_;
      }
      /**
       * <pre>
       *钟表
       * </pre>
       *
       * <code>int32 horologe = 9;</code>
       * @param value The horologe to set.
       * @return This builder for chaining.
       */
      public Builder setHorologe(int value) {
        
        horologe_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *钟表
       * </pre>
       *
       * <code>int32 horologe = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearHorologe() {
        
        horologe_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.game.message.proto.PlayerInfo)
    }

    // @@protoc_insertion_point(class_scope:com.game.message.proto.PlayerInfo)
    private static final org.tinygame.herostory.msg.PlayerProto.PlayerInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.tinygame.herostory.msg.PlayerProto.PlayerInfo();
    }

    public static org.tinygame.herostory.msg.PlayerProto.PlayerInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerInfo>
        PARSER = new com.google.protobuf.AbstractParser<PlayerInfo>() {
      @java.lang.Override
      public PlayerInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.tinygame.herostory.msg.PlayerProto.PlayerInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PlayerLoginCmdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.game.message.proto.PlayerLoginCmd)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string puid = 1;</code>
     * @return The puid.
     */
    java.lang.String getPuid();
    /**
     * <code>string puid = 1;</code>
     * @return The bytes for puid.
     */
    com.google.protobuf.ByteString
        getPuidBytes();

    /**
     * <code>int64 playerId = 2;</code>
     * @return The playerId.
     */
    long getPlayerId();

    /**
     * <code>int32 sessionID = 3;</code>
     * @return The sessionID.
     */
    int getSessionID();
  }
  /**
   * <pre>
   *请求登录
   * </pre>
   *
   * Protobuf type {@code com.game.message.proto.PlayerLoginCmd}
   */
  public static final class PlayerLoginCmd extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.game.message.proto.PlayerLoginCmd)
      PlayerLoginCmdOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlayerLoginCmd.newBuilder() to construct.
    private PlayerLoginCmd(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerLoginCmd() {
      puid_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PlayerLoginCmd();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerLoginCmd(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              puid_ = s;
              break;
            }
            case 16: {

              playerId_ = input.readInt64();
              break;
            }
            case 24: {

              sessionID_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tinygame.herostory.msg.PlayerProto.internal_static_com_game_message_proto_PlayerLoginCmd_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tinygame.herostory.msg.PlayerProto.internal_static_com_game_message_proto_PlayerLoginCmd_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tinygame.herostory.msg.PlayerProto.PlayerLoginCmd.class, org.tinygame.herostory.msg.PlayerProto.PlayerLoginCmd.Builder.class);
    }

    public static final int PUID_FIELD_NUMBER = 1;
    private volatile java.lang.Object puid_;
    /**
     * <code>string puid = 1;</code>
     * @return The puid.
     */
    @java.lang.Override
    public java.lang.String getPuid() {
      java.lang.Object ref = puid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        puid_ = s;
        return s;
      }
    }
    /**
     * <code>string puid = 1;</code>
     * @return The bytes for puid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPuidBytes() {
      java.lang.Object ref = puid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        puid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLAYERID_FIELD_NUMBER = 2;
    private long playerId_;
    /**
     * <code>int64 playerId = 2;</code>
     * @return The playerId.
     */
    @java.lang.Override
    public long getPlayerId() {
      return playerId_;
    }

    public static final int SESSIONID_FIELD_NUMBER = 3;
    private int sessionID_;
    /**
     * <code>int32 sessionID = 3;</code>
     * @return The sessionID.
     */
    @java.lang.Override
    public int getSessionID() {
      return sessionID_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(puid_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, puid_);
      }
      if (playerId_ != 0L) {
        output.writeInt64(2, playerId_);
      }
      if (sessionID_ != 0) {
        output.writeInt32(3, sessionID_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(puid_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, puid_);
      }
      if (playerId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, playerId_);
      }
      if (sessionID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, sessionID_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.tinygame.herostory.msg.PlayerProto.PlayerLoginCmd)) {
        return super.equals(obj);
      }
      org.tinygame.herostory.msg.PlayerProto.PlayerLoginCmd other = (org.tinygame.herostory.msg.PlayerProto.PlayerLoginCmd) obj;

      if (!getPuid()
          .equals(other.getPuid())) return false;
      if (getPlayerId()
          != other.getPlayerId()) return false;
      if (getSessionID()
          != other.getSessionID()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PUID_FIELD_NUMBER;
      hash = (53 * hash) + getPuid().hashCode();
      hash = (37 * hash) + PLAYERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPlayerId());
      hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
      hash = (53 * hash) + getSessionID();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.tinygame.herostory.msg.PlayerProto.PlayerLoginCmd parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tinygame.herostory.msg.PlayerProto.PlayerLoginCmd parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tinygame.herostory.msg.PlayerProto.PlayerLoginCmd parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tinygame.herostory.msg.PlayerProto.PlayerLoginCmd parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tinygame.herostory.msg.PlayerProto.PlayerLoginCmd parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tinygame.herostory.msg.PlayerProto.PlayerLoginCmd parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tinygame.herostory.msg.PlayerProto.PlayerLoginCmd parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tinygame.herostory.msg.PlayerProto.PlayerLoginCmd parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tinygame.herostory.msg.PlayerProto.PlayerLoginCmd parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.tinygame.herostory.msg.PlayerProto.PlayerLoginCmd parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tinygame.herostory.msg.PlayerProto.PlayerLoginCmd parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tinygame.herostory.msg.PlayerProto.PlayerLoginCmd parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.tinygame.herostory.msg.PlayerProto.PlayerLoginCmd prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *请求登录
     * </pre>
     *
     * Protobuf type {@code com.game.message.proto.PlayerLoginCmd}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.game.message.proto.PlayerLoginCmd)
        org.tinygame.herostory.msg.PlayerProto.PlayerLoginCmdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tinygame.herostory.msg.PlayerProto.internal_static_com_game_message_proto_PlayerLoginCmd_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tinygame.herostory.msg.PlayerProto.internal_static_com_game_message_proto_PlayerLoginCmd_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tinygame.herostory.msg.PlayerProto.PlayerLoginCmd.class, org.tinygame.herostory.msg.PlayerProto.PlayerLoginCmd.Builder.class);
      }

      // Construct using org.tinygame.herostory.msg.PlayerProto.PlayerLoginCmd.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        puid_ = "";

        playerId_ = 0L;

        sessionID_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tinygame.herostory.msg.PlayerProto.internal_static_com_game_message_proto_PlayerLoginCmd_descriptor;
      }

      @java.lang.Override
      public org.tinygame.herostory.msg.PlayerProto.PlayerLoginCmd getDefaultInstanceForType() {
        return org.tinygame.herostory.msg.PlayerProto.PlayerLoginCmd.getDefaultInstance();
      }

      @java.lang.Override
      public org.tinygame.herostory.msg.PlayerProto.PlayerLoginCmd build() {
        org.tinygame.herostory.msg.PlayerProto.PlayerLoginCmd result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.tinygame.herostory.msg.PlayerProto.PlayerLoginCmd buildPartial() {
        org.tinygame.herostory.msg.PlayerProto.PlayerLoginCmd result = new org.tinygame.herostory.msg.PlayerProto.PlayerLoginCmd(this);
        result.puid_ = puid_;
        result.playerId_ = playerId_;
        result.sessionID_ = sessionID_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tinygame.herostory.msg.PlayerProto.PlayerLoginCmd) {
          return mergeFrom((org.tinygame.herostory.msg.PlayerProto.PlayerLoginCmd)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tinygame.herostory.msg.PlayerProto.PlayerLoginCmd other) {
        if (other == org.tinygame.herostory.msg.PlayerProto.PlayerLoginCmd.getDefaultInstance()) return this;
        if (!other.getPuid().isEmpty()) {
          puid_ = other.puid_;
          onChanged();
        }
        if (other.getPlayerId() != 0L) {
          setPlayerId(other.getPlayerId());
        }
        if (other.getSessionID() != 0) {
          setSessionID(other.getSessionID());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tinygame.herostory.msg.PlayerProto.PlayerLoginCmd parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tinygame.herostory.msg.PlayerProto.PlayerLoginCmd) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object puid_ = "";
      /**
       * <code>string puid = 1;</code>
       * @return The puid.
       */
      public java.lang.String getPuid() {
        java.lang.Object ref = puid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          puid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string puid = 1;</code>
       * @return The bytes for puid.
       */
      public com.google.protobuf.ByteString
          getPuidBytes() {
        java.lang.Object ref = puid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          puid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string puid = 1;</code>
       * @param value The puid to set.
       * @return This builder for chaining.
       */
      public Builder setPuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        puid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string puid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPuid() {
        
        puid_ = getDefaultInstance().getPuid();
        onChanged();
        return this;
      }
      /**
       * <code>string puid = 1;</code>
       * @param value The bytes for puid to set.
       * @return This builder for chaining.
       */
      public Builder setPuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        puid_ = value;
        onChanged();
        return this;
      }

      private long playerId_ ;
      /**
       * <code>int64 playerId = 2;</code>
       * @return The playerId.
       */
      @java.lang.Override
      public long getPlayerId() {
        return playerId_;
      }
      /**
       * <code>int64 playerId = 2;</code>
       * @param value The playerId to set.
       * @return This builder for chaining.
       */
      public Builder setPlayerId(long value) {
        
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 playerId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlayerId() {
        
        playerId_ = 0L;
        onChanged();
        return this;
      }

      private int sessionID_ ;
      /**
       * <code>int32 sessionID = 3;</code>
       * @return The sessionID.
       */
      @java.lang.Override
      public int getSessionID() {
        return sessionID_;
      }
      /**
       * <code>int32 sessionID = 3;</code>
       * @param value The sessionID to set.
       * @return This builder for chaining.
       */
      public Builder setSessionID(int value) {
        
        sessionID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 sessionID = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSessionID() {
        
        sessionID_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.game.message.proto.PlayerLoginCmd)
    }

    // @@protoc_insertion_point(class_scope:com.game.message.proto.PlayerLoginCmd)
    private static final org.tinygame.herostory.msg.PlayerProto.PlayerLoginCmd DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.tinygame.herostory.msg.PlayerProto.PlayerLoginCmd();
    }

    public static org.tinygame.herostory.msg.PlayerProto.PlayerLoginCmd getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerLoginCmd>
        PARSER = new com.google.protobuf.AbstractParser<PlayerLoginCmd>() {
      @java.lang.Override
      public PlayerLoginCmd parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerLoginCmd(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerLoginCmd> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerLoginCmd> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.tinygame.herostory.msg.PlayerProto.PlayerLoginCmd getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PlayerLoginRetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.game.message.proto.PlayerLoginRet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 result = 1;</code>
     * @return The result.
     */
    int getResult();

    /**
     * <code>int64 playerId = 2;</code>
     * @return The playerId.
     */
    long getPlayerId();

    /**
     * <code>.com.game.message.proto.PlayerInfo playerInfo = 3;</code>
     * @return Whether the playerInfo field is set.
     */
    boolean hasPlayerInfo();
    /**
     * <code>.com.game.message.proto.PlayerInfo playerInfo = 3;</code>
     * @return The playerInfo.
     */
    org.tinygame.herostory.msg.PlayerProto.PlayerInfo getPlayerInfo();
    /**
     * <code>.com.game.message.proto.PlayerInfo playerInfo = 3;</code>
     */
    org.tinygame.herostory.msg.PlayerProto.PlayerInfoOrBuilder getPlayerInfoOrBuilder();
  }
  /**
   * <pre>
   *回复登录
   * </pre>
   *
   * Protobuf type {@code com.game.message.proto.PlayerLoginRet}
   */
  public static final class PlayerLoginRet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.game.message.proto.PlayerLoginRet)
      PlayerLoginRetOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlayerLoginRet.newBuilder() to construct.
    private PlayerLoginRet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerLoginRet() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PlayerLoginRet();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerLoginRet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              result_ = input.readInt32();
              break;
            }
            case 16: {

              playerId_ = input.readInt64();
              break;
            }
            case 26: {
              org.tinygame.herostory.msg.PlayerProto.PlayerInfo.Builder subBuilder = null;
              if (playerInfo_ != null) {
                subBuilder = playerInfo_.toBuilder();
              }
              playerInfo_ = input.readMessage(org.tinygame.herostory.msg.PlayerProto.PlayerInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(playerInfo_);
                playerInfo_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tinygame.herostory.msg.PlayerProto.internal_static_com_game_message_proto_PlayerLoginRet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tinygame.herostory.msg.PlayerProto.internal_static_com_game_message_proto_PlayerLoginRet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tinygame.herostory.msg.PlayerProto.PlayerLoginRet.class, org.tinygame.herostory.msg.PlayerProto.PlayerLoginRet.Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <code>int32 result = 1;</code>
     * @return The result.
     */
    @java.lang.Override
    public int getResult() {
      return result_;
    }

    public static final int PLAYERID_FIELD_NUMBER = 2;
    private long playerId_;
    /**
     * <code>int64 playerId = 2;</code>
     * @return The playerId.
     */
    @java.lang.Override
    public long getPlayerId() {
      return playerId_;
    }

    public static final int PLAYERINFO_FIELD_NUMBER = 3;
    private org.tinygame.herostory.msg.PlayerProto.PlayerInfo playerInfo_;
    /**
     * <code>.com.game.message.proto.PlayerInfo playerInfo = 3;</code>
     * @return Whether the playerInfo field is set.
     */
    @java.lang.Override
    public boolean hasPlayerInfo() {
      return playerInfo_ != null;
    }
    /**
     * <code>.com.game.message.proto.PlayerInfo playerInfo = 3;</code>
     * @return The playerInfo.
     */
    @java.lang.Override
    public org.tinygame.herostory.msg.PlayerProto.PlayerInfo getPlayerInfo() {
      return playerInfo_ == null ? org.tinygame.herostory.msg.PlayerProto.PlayerInfo.getDefaultInstance() : playerInfo_;
    }
    /**
     * <code>.com.game.message.proto.PlayerInfo playerInfo = 3;</code>
     */
    @java.lang.Override
    public org.tinygame.herostory.msg.PlayerProto.PlayerInfoOrBuilder getPlayerInfoOrBuilder() {
      return getPlayerInfo();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (result_ != 0) {
        output.writeInt32(1, result_);
      }
      if (playerId_ != 0L) {
        output.writeInt64(2, playerId_);
      }
      if (playerInfo_ != null) {
        output.writeMessage(3, getPlayerInfo());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (result_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, result_);
      }
      if (playerId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, playerId_);
      }
      if (playerInfo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getPlayerInfo());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.tinygame.herostory.msg.PlayerProto.PlayerLoginRet)) {
        return super.equals(obj);
      }
      org.tinygame.herostory.msg.PlayerProto.PlayerLoginRet other = (org.tinygame.herostory.msg.PlayerProto.PlayerLoginRet) obj;

      if (getResult()
          != other.getResult()) return false;
      if (getPlayerId()
          != other.getPlayerId()) return false;
      if (hasPlayerInfo() != other.hasPlayerInfo()) return false;
      if (hasPlayerInfo()) {
        if (!getPlayerInfo()
            .equals(other.getPlayerInfo())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult();
      hash = (37 * hash) + PLAYERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPlayerId());
      if (hasPlayerInfo()) {
        hash = (37 * hash) + PLAYERINFO_FIELD_NUMBER;
        hash = (53 * hash) + getPlayerInfo().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.tinygame.herostory.msg.PlayerProto.PlayerLoginRet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tinygame.herostory.msg.PlayerProto.PlayerLoginRet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tinygame.herostory.msg.PlayerProto.PlayerLoginRet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tinygame.herostory.msg.PlayerProto.PlayerLoginRet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tinygame.herostory.msg.PlayerProto.PlayerLoginRet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tinygame.herostory.msg.PlayerProto.PlayerLoginRet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tinygame.herostory.msg.PlayerProto.PlayerLoginRet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tinygame.herostory.msg.PlayerProto.PlayerLoginRet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tinygame.herostory.msg.PlayerProto.PlayerLoginRet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.tinygame.herostory.msg.PlayerProto.PlayerLoginRet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tinygame.herostory.msg.PlayerProto.PlayerLoginRet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tinygame.herostory.msg.PlayerProto.PlayerLoginRet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.tinygame.herostory.msg.PlayerProto.PlayerLoginRet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *回复登录
     * </pre>
     *
     * Protobuf type {@code com.game.message.proto.PlayerLoginRet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.game.message.proto.PlayerLoginRet)
        org.tinygame.herostory.msg.PlayerProto.PlayerLoginRetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tinygame.herostory.msg.PlayerProto.internal_static_com_game_message_proto_PlayerLoginRet_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tinygame.herostory.msg.PlayerProto.internal_static_com_game_message_proto_PlayerLoginRet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tinygame.herostory.msg.PlayerProto.PlayerLoginRet.class, org.tinygame.herostory.msg.PlayerProto.PlayerLoginRet.Builder.class);
      }

      // Construct using org.tinygame.herostory.msg.PlayerProto.PlayerLoginRet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        result_ = 0;

        playerId_ = 0L;

        if (playerInfoBuilder_ == null) {
          playerInfo_ = null;
        } else {
          playerInfo_ = null;
          playerInfoBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tinygame.herostory.msg.PlayerProto.internal_static_com_game_message_proto_PlayerLoginRet_descriptor;
      }

      @java.lang.Override
      public org.tinygame.herostory.msg.PlayerProto.PlayerLoginRet getDefaultInstanceForType() {
        return org.tinygame.herostory.msg.PlayerProto.PlayerLoginRet.getDefaultInstance();
      }

      @java.lang.Override
      public org.tinygame.herostory.msg.PlayerProto.PlayerLoginRet build() {
        org.tinygame.herostory.msg.PlayerProto.PlayerLoginRet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.tinygame.herostory.msg.PlayerProto.PlayerLoginRet buildPartial() {
        org.tinygame.herostory.msg.PlayerProto.PlayerLoginRet result = new org.tinygame.herostory.msg.PlayerProto.PlayerLoginRet(this);
        result.result_ = result_;
        result.playerId_ = playerId_;
        if (playerInfoBuilder_ == null) {
          result.playerInfo_ = playerInfo_;
        } else {
          result.playerInfo_ = playerInfoBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tinygame.herostory.msg.PlayerProto.PlayerLoginRet) {
          return mergeFrom((org.tinygame.herostory.msg.PlayerProto.PlayerLoginRet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tinygame.herostory.msg.PlayerProto.PlayerLoginRet other) {
        if (other == org.tinygame.herostory.msg.PlayerProto.PlayerLoginRet.getDefaultInstance()) return this;
        if (other.getResult() != 0) {
          setResult(other.getResult());
        }
        if (other.getPlayerId() != 0L) {
          setPlayerId(other.getPlayerId());
        }
        if (other.hasPlayerInfo()) {
          mergePlayerInfo(other.getPlayerInfo());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tinygame.herostory.msg.PlayerProto.PlayerLoginRet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tinygame.herostory.msg.PlayerProto.PlayerLoginRet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int result_ ;
      /**
       * <code>int32 result = 1;</code>
       * @return The result.
       */
      @java.lang.Override
      public int getResult() {
        return result_;
      }
      /**
       * <code>int32 result = 1;</code>
       * @param value The result to set.
       * @return This builder for chaining.
       */
      public Builder setResult(int value) {
        
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 result = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResult() {
        
        result_ = 0;
        onChanged();
        return this;
      }

      private long playerId_ ;
      /**
       * <code>int64 playerId = 2;</code>
       * @return The playerId.
       */
      @java.lang.Override
      public long getPlayerId() {
        return playerId_;
      }
      /**
       * <code>int64 playerId = 2;</code>
       * @param value The playerId to set.
       * @return This builder for chaining.
       */
      public Builder setPlayerId(long value) {
        
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 playerId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlayerId() {
        
        playerId_ = 0L;
        onChanged();
        return this;
      }

      private org.tinygame.herostory.msg.PlayerProto.PlayerInfo playerInfo_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.tinygame.herostory.msg.PlayerProto.PlayerInfo, org.tinygame.herostory.msg.PlayerProto.PlayerInfo.Builder, org.tinygame.herostory.msg.PlayerProto.PlayerInfoOrBuilder> playerInfoBuilder_;
      /**
       * <code>.com.game.message.proto.PlayerInfo playerInfo = 3;</code>
       * @return Whether the playerInfo field is set.
       */
      public boolean hasPlayerInfo() {
        return playerInfoBuilder_ != null || playerInfo_ != null;
      }
      /**
       * <code>.com.game.message.proto.PlayerInfo playerInfo = 3;</code>
       * @return The playerInfo.
       */
      public org.tinygame.herostory.msg.PlayerProto.PlayerInfo getPlayerInfo() {
        if (playerInfoBuilder_ == null) {
          return playerInfo_ == null ? org.tinygame.herostory.msg.PlayerProto.PlayerInfo.getDefaultInstance() : playerInfo_;
        } else {
          return playerInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.game.message.proto.PlayerInfo playerInfo = 3;</code>
       */
      public Builder setPlayerInfo(org.tinygame.herostory.msg.PlayerProto.PlayerInfo value) {
        if (playerInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          playerInfo_ = value;
          onChanged();
        } else {
          playerInfoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.game.message.proto.PlayerInfo playerInfo = 3;</code>
       */
      public Builder setPlayerInfo(
          org.tinygame.herostory.msg.PlayerProto.PlayerInfo.Builder builderForValue) {
        if (playerInfoBuilder_ == null) {
          playerInfo_ = builderForValue.build();
          onChanged();
        } else {
          playerInfoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.game.message.proto.PlayerInfo playerInfo = 3;</code>
       */
      public Builder mergePlayerInfo(org.tinygame.herostory.msg.PlayerProto.PlayerInfo value) {
        if (playerInfoBuilder_ == null) {
          if (playerInfo_ != null) {
            playerInfo_ =
              org.tinygame.herostory.msg.PlayerProto.PlayerInfo.newBuilder(playerInfo_).mergeFrom(value).buildPartial();
          } else {
            playerInfo_ = value;
          }
          onChanged();
        } else {
          playerInfoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.game.message.proto.PlayerInfo playerInfo = 3;</code>
       */
      public Builder clearPlayerInfo() {
        if (playerInfoBuilder_ == null) {
          playerInfo_ = null;
          onChanged();
        } else {
          playerInfo_ = null;
          playerInfoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.game.message.proto.PlayerInfo playerInfo = 3;</code>
       */
      public org.tinygame.herostory.msg.PlayerProto.PlayerInfo.Builder getPlayerInfoBuilder() {
        
        onChanged();
        return getPlayerInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.game.message.proto.PlayerInfo playerInfo = 3;</code>
       */
      public org.tinygame.herostory.msg.PlayerProto.PlayerInfoOrBuilder getPlayerInfoOrBuilder() {
        if (playerInfoBuilder_ != null) {
          return playerInfoBuilder_.getMessageOrBuilder();
        } else {
          return playerInfo_ == null ?
              org.tinygame.herostory.msg.PlayerProto.PlayerInfo.getDefaultInstance() : playerInfo_;
        }
      }
      /**
       * <code>.com.game.message.proto.PlayerInfo playerInfo = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.tinygame.herostory.msg.PlayerProto.PlayerInfo, org.tinygame.herostory.msg.PlayerProto.PlayerInfo.Builder, org.tinygame.herostory.msg.PlayerProto.PlayerInfoOrBuilder> 
          getPlayerInfoFieldBuilder() {
        if (playerInfoBuilder_ == null) {
          playerInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.tinygame.herostory.msg.PlayerProto.PlayerInfo, org.tinygame.herostory.msg.PlayerProto.PlayerInfo.Builder, org.tinygame.herostory.msg.PlayerProto.PlayerInfoOrBuilder>(
                  getPlayerInfo(),
                  getParentForChildren(),
                  isClean());
          playerInfo_ = null;
        }
        return playerInfoBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.game.message.proto.PlayerLoginRet)
    }

    // @@protoc_insertion_point(class_scope:com.game.message.proto.PlayerLoginRet)
    private static final org.tinygame.herostory.msg.PlayerProto.PlayerLoginRet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.tinygame.herostory.msg.PlayerProto.PlayerLoginRet();
    }

    public static org.tinygame.herostory.msg.PlayerProto.PlayerLoginRet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerLoginRet>
        PARSER = new com.google.protobuf.AbstractParser<PlayerLoginRet>() {
      @java.lang.Override
      public PlayerLoginRet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerLoginRet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerLoginRet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerLoginRet> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.tinygame.herostory.msg.PlayerProto.PlayerLoginRet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_game_message_proto_PlayerInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_game_message_proto_PlayerInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_game_message_proto_PlayerLoginCmd_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_game_message_proto_PlayerLoginCmd_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_game_message_proto_PlayerLoginRet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_game_message_proto_PlayerLoginRet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Player.proto\022\026com.game.message.proto\"\235" +
      "\001\n\nPlayerInfo\022\020\n\010playerId\030\001 \001(\003\022\014\n\004cash\030" +
      "\002 \001(\005\022\r\n\005money\030\003 \001(\003\022\014\n\004gold\030\004 \001(\005\022\014\n\004na" +
      "me\030\005 \001(\t\022\014\n\004head\030\006 \001(\005\022\021\n\tloginTime\030\007 \001(" +
      "\003\022\021\n\tsignboard\030\010 \001(\005\022\020\n\010horologe\030\t \001(\005\"C" +
      "\n\016PlayerLoginCmd\022\014\n\004puid\030\001 \001(\t\022\020\n\010player" +
      "Id\030\002 \001(\003\022\021\n\tsessionID\030\003 \001(\005\"j\n\016PlayerLog" +
      "inRet\022\016\n\006result\030\001 \001(\005\022\020\n\010playerId\030\002 \001(\003\022" +
      "6\n\nplayerInfo\030\003 \001(\0132\".com.game.message.p" +
      "roto.PlayerInfoB)\n\032org.tinygame.herostor" +
      "y.msgB\013PlayerProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_game_message_proto_PlayerInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_game_message_proto_PlayerInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_game_message_proto_PlayerInfo_descriptor,
        new java.lang.String[] { "PlayerId", "Cash", "Money", "Gold", "Name", "Head", "LoginTime", "Signboard", "Horologe", });
    internal_static_com_game_message_proto_PlayerLoginCmd_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_game_message_proto_PlayerLoginCmd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_game_message_proto_PlayerLoginCmd_descriptor,
        new java.lang.String[] { "Puid", "PlayerId", "SessionID", });
    internal_static_com_game_message_proto_PlayerLoginRet_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_game_message_proto_PlayerLoginRet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_game_message_proto_PlayerLoginRet_descriptor,
        new java.lang.String[] { "Result", "PlayerId", "PlayerInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
