// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Table.proto

package org.tinygame.herostory.msg;

public final class TableProto {
  private TableProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface tableinfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.game.message.proto.tableinfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 type = 1;</code>
     * @return The type.
     */
    int getType();

    /**
     * <code>bool dirty = 2;</code>
     * @return The dirty.
     */
    boolean getDirty();
  }
  /**
   * Protobuf type {@code com.game.message.proto.tableinfo}
   */
  public static final class tableinfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.game.message.proto.tableinfo)
      tableinfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use tableinfo.newBuilder() to construct.
    private tableinfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private tableinfo() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new tableinfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private tableinfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              type_ = input.readInt32();
              break;
            }
            case 16: {

              dirty_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tinygame.herostory.msg.TableProto.internal_static_com_game_message_proto_tableinfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tinygame.herostory.msg.TableProto.internal_static_com_game_message_proto_tableinfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tinygame.herostory.msg.TableProto.tableinfo.class, org.tinygame.herostory.msg.TableProto.tableinfo.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>int32 type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }

    public static final int DIRTY_FIELD_NUMBER = 2;
    private boolean dirty_;
    /**
     * <code>bool dirty = 2;</code>
     * @return The dirty.
     */
    @java.lang.Override
    public boolean getDirty() {
      return dirty_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != 0) {
        output.writeInt32(1, type_);
      }
      if (dirty_ != false) {
        output.writeBool(2, dirty_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (dirty_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, dirty_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.tinygame.herostory.msg.TableProto.tableinfo)) {
        return super.equals(obj);
      }
      org.tinygame.herostory.msg.TableProto.tableinfo other = (org.tinygame.herostory.msg.TableProto.tableinfo) obj;

      if (getType()
          != other.getType()) return false;
      if (getDirty()
          != other.getDirty()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + DIRTY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getDirty());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.tinygame.herostory.msg.TableProto.tableinfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tinygame.herostory.msg.TableProto.tableinfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tinygame.herostory.msg.TableProto.tableinfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tinygame.herostory.msg.TableProto.tableinfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tinygame.herostory.msg.TableProto.tableinfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tinygame.herostory.msg.TableProto.tableinfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tinygame.herostory.msg.TableProto.tableinfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tinygame.herostory.msg.TableProto.tableinfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tinygame.herostory.msg.TableProto.tableinfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.tinygame.herostory.msg.TableProto.tableinfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tinygame.herostory.msg.TableProto.tableinfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tinygame.herostory.msg.TableProto.tableinfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.tinygame.herostory.msg.TableProto.tableinfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.game.message.proto.tableinfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.game.message.proto.tableinfo)
        org.tinygame.herostory.msg.TableProto.tableinfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tinygame.herostory.msg.TableProto.internal_static_com_game_message_proto_tableinfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tinygame.herostory.msg.TableProto.internal_static_com_game_message_proto_tableinfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tinygame.herostory.msg.TableProto.tableinfo.class, org.tinygame.herostory.msg.TableProto.tableinfo.Builder.class);
      }

      // Construct using org.tinygame.herostory.msg.TableProto.tableinfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        dirty_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tinygame.herostory.msg.TableProto.internal_static_com_game_message_proto_tableinfo_descriptor;
      }

      @java.lang.Override
      public org.tinygame.herostory.msg.TableProto.tableinfo getDefaultInstanceForType() {
        return org.tinygame.herostory.msg.TableProto.tableinfo.getDefaultInstance();
      }

      @java.lang.Override
      public org.tinygame.herostory.msg.TableProto.tableinfo build() {
        org.tinygame.herostory.msg.TableProto.tableinfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.tinygame.herostory.msg.TableProto.tableinfo buildPartial() {
        org.tinygame.herostory.msg.TableProto.tableinfo result = new org.tinygame.herostory.msg.TableProto.tableinfo(this);
        result.type_ = type_;
        result.dirty_ = dirty_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tinygame.herostory.msg.TableProto.tableinfo) {
          return mergeFrom((org.tinygame.herostory.msg.TableProto.tableinfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tinygame.herostory.msg.TableProto.tableinfo other) {
        if (other == org.tinygame.herostory.msg.TableProto.tableinfo.getDefaultInstance()) return this;
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (other.getDirty() != false) {
          setDirty(other.getDirty());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tinygame.herostory.msg.TableProto.tableinfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tinygame.herostory.msg.TableProto.tableinfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ ;
      /**
       * <code>int32 type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public int getType() {
        return type_;
      }
      /**
       * <code>int32 type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private boolean dirty_ ;
      /**
       * <code>bool dirty = 2;</code>
       * @return The dirty.
       */
      @java.lang.Override
      public boolean getDirty() {
        return dirty_;
      }
      /**
       * <code>bool dirty = 2;</code>
       * @param value The dirty to set.
       * @return This builder for chaining.
       */
      public Builder setDirty(boolean value) {
        
        dirty_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool dirty = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDirty() {
        
        dirty_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.game.message.proto.tableinfo)
    }

    // @@protoc_insertion_point(class_scope:com.game.message.proto.tableinfo)
    private static final org.tinygame.herostory.msg.TableProto.tableinfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.tinygame.herostory.msg.TableProto.tableinfo();
    }

    public static org.tinygame.herostory.msg.TableProto.tableinfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<tableinfo>
        PARSER = new com.google.protobuf.AbstractParser<tableinfo>() {
      @java.lang.Override
      public tableinfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new tableinfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<tableinfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<tableinfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.tinygame.herostory.msg.TableProto.tableinfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CleanTableCmdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.game.message.proto.CleanTableCmd)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 playerId = 1;</code>
     * @return The playerId.
     */
    long getPlayerId();

    /**
     * <pre>
     *餐桌号
     * </pre>
     *
     * <code>int32 number = 2;</code>
     * @return The number.
     */
    int getNumber();
  }
  /**
   * <pre>
   * 清理餐桌
   * </pre>
   *
   * Protobuf type {@code com.game.message.proto.CleanTableCmd}
   */
  public static final class CleanTableCmd extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.game.message.proto.CleanTableCmd)
      CleanTableCmdOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CleanTableCmd.newBuilder() to construct.
    private CleanTableCmd(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CleanTableCmd() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CleanTableCmd();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CleanTableCmd(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              playerId_ = input.readInt64();
              break;
            }
            case 16: {

              number_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tinygame.herostory.msg.TableProto.internal_static_com_game_message_proto_CleanTableCmd_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tinygame.herostory.msg.TableProto.internal_static_com_game_message_proto_CleanTableCmd_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tinygame.herostory.msg.TableProto.CleanTableCmd.class, org.tinygame.herostory.msg.TableProto.CleanTableCmd.Builder.class);
    }

    public static final int PLAYERID_FIELD_NUMBER = 1;
    private long playerId_;
    /**
     * <code>int64 playerId = 1;</code>
     * @return The playerId.
     */
    @java.lang.Override
    public long getPlayerId() {
      return playerId_;
    }

    public static final int NUMBER_FIELD_NUMBER = 2;
    private int number_;
    /**
     * <pre>
     *餐桌号
     * </pre>
     *
     * <code>int32 number = 2;</code>
     * @return The number.
     */
    @java.lang.Override
    public int getNumber() {
      return number_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (playerId_ != 0L) {
        output.writeInt64(1, playerId_);
      }
      if (number_ != 0) {
        output.writeInt32(2, number_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (playerId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, playerId_);
      }
      if (number_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, number_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.tinygame.herostory.msg.TableProto.CleanTableCmd)) {
        return super.equals(obj);
      }
      org.tinygame.herostory.msg.TableProto.CleanTableCmd other = (org.tinygame.herostory.msg.TableProto.CleanTableCmd) obj;

      if (getPlayerId()
          != other.getPlayerId()) return false;
      if (getNumber()
          != other.getNumber()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PLAYERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPlayerId());
      hash = (37 * hash) + NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getNumber();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.tinygame.herostory.msg.TableProto.CleanTableCmd parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tinygame.herostory.msg.TableProto.CleanTableCmd parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tinygame.herostory.msg.TableProto.CleanTableCmd parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tinygame.herostory.msg.TableProto.CleanTableCmd parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tinygame.herostory.msg.TableProto.CleanTableCmd parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tinygame.herostory.msg.TableProto.CleanTableCmd parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tinygame.herostory.msg.TableProto.CleanTableCmd parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tinygame.herostory.msg.TableProto.CleanTableCmd parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tinygame.herostory.msg.TableProto.CleanTableCmd parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.tinygame.herostory.msg.TableProto.CleanTableCmd parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tinygame.herostory.msg.TableProto.CleanTableCmd parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tinygame.herostory.msg.TableProto.CleanTableCmd parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.tinygame.herostory.msg.TableProto.CleanTableCmd prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 清理餐桌
     * </pre>
     *
     * Protobuf type {@code com.game.message.proto.CleanTableCmd}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.game.message.proto.CleanTableCmd)
        org.tinygame.herostory.msg.TableProto.CleanTableCmdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tinygame.herostory.msg.TableProto.internal_static_com_game_message_proto_CleanTableCmd_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tinygame.herostory.msg.TableProto.internal_static_com_game_message_proto_CleanTableCmd_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tinygame.herostory.msg.TableProto.CleanTableCmd.class, org.tinygame.herostory.msg.TableProto.CleanTableCmd.Builder.class);
      }

      // Construct using org.tinygame.herostory.msg.TableProto.CleanTableCmd.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        playerId_ = 0L;

        number_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tinygame.herostory.msg.TableProto.internal_static_com_game_message_proto_CleanTableCmd_descriptor;
      }

      @java.lang.Override
      public org.tinygame.herostory.msg.TableProto.CleanTableCmd getDefaultInstanceForType() {
        return org.tinygame.herostory.msg.TableProto.CleanTableCmd.getDefaultInstance();
      }

      @java.lang.Override
      public org.tinygame.herostory.msg.TableProto.CleanTableCmd build() {
        org.tinygame.herostory.msg.TableProto.CleanTableCmd result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.tinygame.herostory.msg.TableProto.CleanTableCmd buildPartial() {
        org.tinygame.herostory.msg.TableProto.CleanTableCmd result = new org.tinygame.herostory.msg.TableProto.CleanTableCmd(this);
        result.playerId_ = playerId_;
        result.number_ = number_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tinygame.herostory.msg.TableProto.CleanTableCmd) {
          return mergeFrom((org.tinygame.herostory.msg.TableProto.CleanTableCmd)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tinygame.herostory.msg.TableProto.CleanTableCmd other) {
        if (other == org.tinygame.herostory.msg.TableProto.CleanTableCmd.getDefaultInstance()) return this;
        if (other.getPlayerId() != 0L) {
          setPlayerId(other.getPlayerId());
        }
        if (other.getNumber() != 0) {
          setNumber(other.getNumber());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tinygame.herostory.msg.TableProto.CleanTableCmd parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tinygame.herostory.msg.TableProto.CleanTableCmd) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long playerId_ ;
      /**
       * <code>int64 playerId = 1;</code>
       * @return The playerId.
       */
      @java.lang.Override
      public long getPlayerId() {
        return playerId_;
      }
      /**
       * <code>int64 playerId = 1;</code>
       * @param value The playerId to set.
       * @return This builder for chaining.
       */
      public Builder setPlayerId(long value) {
        
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 playerId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlayerId() {
        
        playerId_ = 0L;
        onChanged();
        return this;
      }

      private int number_ ;
      /**
       * <pre>
       *餐桌号
       * </pre>
       *
       * <code>int32 number = 2;</code>
       * @return The number.
       */
      @java.lang.Override
      public int getNumber() {
        return number_;
      }
      /**
       * <pre>
       *餐桌号
       * </pre>
       *
       * <code>int32 number = 2;</code>
       * @param value The number to set.
       * @return This builder for chaining.
       */
      public Builder setNumber(int value) {
        
        number_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *餐桌号
       * </pre>
       *
       * <code>int32 number = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumber() {
        
        number_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.game.message.proto.CleanTableCmd)
    }

    // @@protoc_insertion_point(class_scope:com.game.message.proto.CleanTableCmd)
    private static final org.tinygame.herostory.msg.TableProto.CleanTableCmd DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.tinygame.herostory.msg.TableProto.CleanTableCmd();
    }

    public static org.tinygame.herostory.msg.TableProto.CleanTableCmd getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CleanTableCmd>
        PARSER = new com.google.protobuf.AbstractParser<CleanTableCmd>() {
      @java.lang.Override
      public CleanTableCmd parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CleanTableCmd(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CleanTableCmd> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CleanTableCmd> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.tinygame.herostory.msg.TableProto.CleanTableCmd getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CleanTableRetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.game.message.proto.CleanTableRet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *返回码
     * </pre>
     *
     * <code>int32 result = 1;</code>
     * @return The result.
     */
    int getResult();

    /**
     * <pre>
     *红包奖励
     * </pre>
     *
     * <code>int32 cash = 2;</code>
     * @return The cash.
     */
    int getCash();
  }
  /**
   * <pre>
   * 清理餐桌返回
   * </pre>
   *
   * Protobuf type {@code com.game.message.proto.CleanTableRet}
   */
  public static final class CleanTableRet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.game.message.proto.CleanTableRet)
      CleanTableRetOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CleanTableRet.newBuilder() to construct.
    private CleanTableRet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CleanTableRet() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CleanTableRet();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CleanTableRet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              result_ = input.readInt32();
              break;
            }
            case 16: {

              cash_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tinygame.herostory.msg.TableProto.internal_static_com_game_message_proto_CleanTableRet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tinygame.herostory.msg.TableProto.internal_static_com_game_message_proto_CleanTableRet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tinygame.herostory.msg.TableProto.CleanTableRet.class, org.tinygame.herostory.msg.TableProto.CleanTableRet.Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <pre>
     *返回码
     * </pre>
     *
     * <code>int32 result = 1;</code>
     * @return The result.
     */
    @java.lang.Override
    public int getResult() {
      return result_;
    }

    public static final int CASH_FIELD_NUMBER = 2;
    private int cash_;
    /**
     * <pre>
     *红包奖励
     * </pre>
     *
     * <code>int32 cash = 2;</code>
     * @return The cash.
     */
    @java.lang.Override
    public int getCash() {
      return cash_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (result_ != 0) {
        output.writeInt32(1, result_);
      }
      if (cash_ != 0) {
        output.writeInt32(2, cash_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (result_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, result_);
      }
      if (cash_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, cash_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.tinygame.herostory.msg.TableProto.CleanTableRet)) {
        return super.equals(obj);
      }
      org.tinygame.herostory.msg.TableProto.CleanTableRet other = (org.tinygame.herostory.msg.TableProto.CleanTableRet) obj;

      if (getResult()
          != other.getResult()) return false;
      if (getCash()
          != other.getCash()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult();
      hash = (37 * hash) + CASH_FIELD_NUMBER;
      hash = (53 * hash) + getCash();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.tinygame.herostory.msg.TableProto.CleanTableRet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tinygame.herostory.msg.TableProto.CleanTableRet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tinygame.herostory.msg.TableProto.CleanTableRet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tinygame.herostory.msg.TableProto.CleanTableRet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tinygame.herostory.msg.TableProto.CleanTableRet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tinygame.herostory.msg.TableProto.CleanTableRet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tinygame.herostory.msg.TableProto.CleanTableRet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tinygame.herostory.msg.TableProto.CleanTableRet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tinygame.herostory.msg.TableProto.CleanTableRet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.tinygame.herostory.msg.TableProto.CleanTableRet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tinygame.herostory.msg.TableProto.CleanTableRet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tinygame.herostory.msg.TableProto.CleanTableRet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.tinygame.herostory.msg.TableProto.CleanTableRet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 清理餐桌返回
     * </pre>
     *
     * Protobuf type {@code com.game.message.proto.CleanTableRet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.game.message.proto.CleanTableRet)
        org.tinygame.herostory.msg.TableProto.CleanTableRetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tinygame.herostory.msg.TableProto.internal_static_com_game_message_proto_CleanTableRet_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tinygame.herostory.msg.TableProto.internal_static_com_game_message_proto_CleanTableRet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tinygame.herostory.msg.TableProto.CleanTableRet.class, org.tinygame.herostory.msg.TableProto.CleanTableRet.Builder.class);
      }

      // Construct using org.tinygame.herostory.msg.TableProto.CleanTableRet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        result_ = 0;

        cash_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tinygame.herostory.msg.TableProto.internal_static_com_game_message_proto_CleanTableRet_descriptor;
      }

      @java.lang.Override
      public org.tinygame.herostory.msg.TableProto.CleanTableRet getDefaultInstanceForType() {
        return org.tinygame.herostory.msg.TableProto.CleanTableRet.getDefaultInstance();
      }

      @java.lang.Override
      public org.tinygame.herostory.msg.TableProto.CleanTableRet build() {
        org.tinygame.herostory.msg.TableProto.CleanTableRet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.tinygame.herostory.msg.TableProto.CleanTableRet buildPartial() {
        org.tinygame.herostory.msg.TableProto.CleanTableRet result = new org.tinygame.herostory.msg.TableProto.CleanTableRet(this);
        result.result_ = result_;
        result.cash_ = cash_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tinygame.herostory.msg.TableProto.CleanTableRet) {
          return mergeFrom((org.tinygame.herostory.msg.TableProto.CleanTableRet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tinygame.herostory.msg.TableProto.CleanTableRet other) {
        if (other == org.tinygame.herostory.msg.TableProto.CleanTableRet.getDefaultInstance()) return this;
        if (other.getResult() != 0) {
          setResult(other.getResult());
        }
        if (other.getCash() != 0) {
          setCash(other.getCash());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tinygame.herostory.msg.TableProto.CleanTableRet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tinygame.herostory.msg.TableProto.CleanTableRet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int result_ ;
      /**
       * <pre>
       *返回码
       * </pre>
       *
       * <code>int32 result = 1;</code>
       * @return The result.
       */
      @java.lang.Override
      public int getResult() {
        return result_;
      }
      /**
       * <pre>
       *返回码
       * </pre>
       *
       * <code>int32 result = 1;</code>
       * @param value The result to set.
       * @return This builder for chaining.
       */
      public Builder setResult(int value) {
        
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *返回码
       * </pre>
       *
       * <code>int32 result = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResult() {
        
        result_ = 0;
        onChanged();
        return this;
      }

      private int cash_ ;
      /**
       * <pre>
       *红包奖励
       * </pre>
       *
       * <code>int32 cash = 2;</code>
       * @return The cash.
       */
      @java.lang.Override
      public int getCash() {
        return cash_;
      }
      /**
       * <pre>
       *红包奖励
       * </pre>
       *
       * <code>int32 cash = 2;</code>
       * @param value The cash to set.
       * @return This builder for chaining.
       */
      public Builder setCash(int value) {
        
        cash_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *红包奖励
       * </pre>
       *
       * <code>int32 cash = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCash() {
        
        cash_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.game.message.proto.CleanTableRet)
    }

    // @@protoc_insertion_point(class_scope:com.game.message.proto.CleanTableRet)
    private static final org.tinygame.herostory.msg.TableProto.CleanTableRet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.tinygame.herostory.msg.TableProto.CleanTableRet();
    }

    public static org.tinygame.herostory.msg.TableProto.CleanTableRet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CleanTableRet>
        PARSER = new com.google.protobuf.AbstractParser<CleanTableRet>() {
      @java.lang.Override
      public CleanTableRet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CleanTableRet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CleanTableRet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CleanTableRet> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.tinygame.herostory.msg.TableProto.CleanTableRet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_game_message_proto_tableinfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_game_message_proto_tableinfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_game_message_proto_CleanTableCmd_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_game_message_proto_CleanTableCmd_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_game_message_proto_CleanTableRet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_game_message_proto_CleanTableRet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Table.proto\022\026com.game.message.proto\"(\n" +
      "\ttableinfo\022\014\n\004type\030\001 \001(\005\022\r\n\005dirty\030\002 \001(\010\"" +
      "1\n\rCleanTableCmd\022\020\n\010playerId\030\001 \001(\003\022\016\n\006nu" +
      "mber\030\002 \001(\005\"-\n\rCleanTableRet\022\016\n\006result\030\001 " +
      "\001(\005\022\014\n\004cash\030\002 \001(\005B(\n\032org.tinygame.herost" +
      "ory.msgB\nTableProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_game_message_proto_tableinfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_game_message_proto_tableinfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_game_message_proto_tableinfo_descriptor,
        new java.lang.String[] { "Type", "Dirty", });
    internal_static_com_game_message_proto_CleanTableCmd_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_game_message_proto_CleanTableCmd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_game_message_proto_CleanTableCmd_descriptor,
        new java.lang.String[] { "PlayerId", "Number", });
    internal_static_com_game_message_proto_CleanTableRet_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_game_message_proto_CleanTableRet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_game_message_proto_CleanTableRet_descriptor,
        new java.lang.String[] { "Result", "Cash", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
